[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["rm -rf node_modules/.vite || true", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.cjs"
