[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "RUN_MODE=worker node dist/index.cjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1
